# Mecanico

taller_editar_mecanico:
    pattern:  /mecanico/editar/{id}
    defaults: { _controller: DonCarTallerBundle:Mecanico:editarMecanico }

taller_listar_mecanico:
    pattern:  /mecanico/listar
    defaults: { _controller: DonCarTallerBundle:Mecanico:listarMecanico }

taller_alta_mecanico:
    pattern:  /mecanico/alta
    defaults: { _controller: DonCarTallerBundle:Mecanico:altaMecanico }

taller_eliminar_mecanico:
    pattern: /mecanico/eliminar/{id}
    defaults: { _controller: DonCarTallerBundle:Mecanico:eliminarMecanico }


#Orden

taller_alta_orden:
    pattern: /orden/alta
    defaults: { _controller: DonCarTallerBundle:Ordenes:altaOrden }

taller_editar_orden:
    pattern: /orden/editar/{id}
    defaults: { _controller: DonCarTallerBundle:Ordenes:editarOrden }

taller_gestion_orden:
    pattern: /orden/gestion
    defaults: { _controller: DonCarTallerBundle:Ordenes:gestionarOrden }

taller_listar_orden_paginada:
    pattern: /orden/listar/pag_{pagina}
    defaults: { _controller: DonCarTallerBundle:Ordenes:listarOrdenPaginada }

taller_listar_orden:
    pattern: /orden/listar
    defaults: 
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /taller/orden/listar/pag_1
        permanent: true

taller_eliminar_orden:
    pattern: /orden/eliminar/{id}
    defaults: { _controller: DonCarTallerBundle:Ordenes:eliminarOrden }


# Varios

taller_operacion_exitosa:
    pattern: /exito
    defaults: { _controller: DonCarTallerBundle:Default:operacionExitosa }

taller_root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /taller/orden/gestion
        permanent: true
