parameters:
#    don_car_taller.example.class: DonCar\TallerBundle\Example

services:
#    don_car_taller.example:
#        class: %don_car_taller.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
