don_car_precios_service:
    resource: "@DonCarPreciosServiceBundle/Resources/config/routing.yml"
    prefix:   /service

don_car_taller:
    resource: "@DonCarTallerBundle/Resources/config/routing.yml"
    prefix:   /taller

