parameters:
#    don_car_precios_service.example.class: DonCar\PreciosServiceBundle\Example

services:
#    don_car_precios_service.example:
#        class: %don_car_precios_service.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
